var restaurants,neighborhoods,cuisines,map,markers=[];document.addEventListener("DOMContentLoaded",function(a){updateRestaurants();fetchNeighborhoods();fetchCuisines();lazyLoadMap()});
var fetchNeighborhoods=function(){DBHelper.fetchNeighborhoods(function(a,c){a?console.error(a):(self.neighborhoods=c,fillNeighborhoodsHTML())})},fillNeighborhoodsHTML=function(a){a=void 0===a?self.neighborhoods:a;var c=document.getElementById("neighborhoods-select");a.forEach(function(a){var e=document.createElement("option");e.innerHTML=a;e.value=a;c.append(e)})},fetchCuisines=function(){DBHelper.fetchCuisines(function(a,c){a?console.error(a):(self.cuisines=c,fillCuisinesHTML())})},fillCuisinesHTML=
function(a){a=void 0===a?self.cuisines:a;var c=document.getElementById("cuisines-select");a.forEach(function(a){var e=document.createElement("option");e.innerHTML=a;e.value=a;c.append(e)})};window.initMap=function(){self.map=new google.maps.Map(document.getElementById("map"),{zoom:12,center:{lat:40.722216,lng:-73.987501},scrollwheel:!1})};
var updateRestaurants=function(){var a=document.getElementById("cuisines-select"),c=document.getElementById("neighborhoods-select");DBHelper.fetchRestaurantByCuisineAndNeighborhood(a[a.selectedIndex].value,c[c.selectedIndex].value,function(a,c){a?console.error(a):(resetRestaurants(c),fillRestaurantsHTML())})},resetRestaurants=function(a){self.restaurants=[];document.getElementById("restaurants-list").innerHTML="";self.markers.forEach(function(a){return a.setMap(null)});self.markers=[];self.restaurants=
a},fillRestaurantsHTML=function(a){a=void 0===a?self.restaurants:a;var c=document.getElementById("restaurants-list");a.forEach(function(a){c.append(createRestaurantHTML(a))});lazyLoadImages();addMarkersToMap()},createRestaurantHTML=function(a){function c(a,b){return fetch(a,{method:"PUT",body:JSON.stringify(b),headers:{"content-type":"application/json"}}).then(function(a){a.json}).catch(function(a){console.log("Could not make favorite restaurant, error: "+a)})}function e(){c(m,{is_favorite:!0}).then(function(){document.getElementById(l).innerHTML=
"Favorite updated: True";console.log("update fav field with value: "+a.is_favorite)}).then(function(a){console.log("restaurant id "+g+" is favorite now ")}).catch(function(a){console.log(a)})}function k(){c(DBHelper.DATABASE_URL+"/"+g,{is_favorite:!1}).then(function(){document.getElementById(l).innerHTML="Favorite updated: False";console.log("update fav field with value: "+a.is_favorite)}).then(function(a){console.log("restaurant id "+g+" is UNfavorite now ")}).catch(function(a){console.log(a)})}
var g=a.id,l="fav"+g,m=DBHelper.DATABASE_URL+"/"+g,h=document.createElement("li");h.className="container-rest-details";var b=document.createElement("div");b.className="column";h.append(b);var d=document.createElement("picture");b.append(d);b=document.createElement("source");b.media="(max-width: 10rem)";b.dataset.srcset=DBHelper.imageUrlForRestaurant(a)+"-128w.jpg";d.append(b);b=document.createElement("source");b.media="(max-width: 30rem)";b.dataset.srcset=DBHelper.imageUrlForRestaurant(a)+"-400w.jpg";
d.append(b);b=document.createElement("source");b.media="(min-width: 30rem)";b.dataset.srcset=DBHelper.imageUrlForRestaurant(a)+"-500w.jpg";d.append(b);b=document.createElement("img");b.className="lazy restaurant-img";b.alt="image of "+a.name+" restaurant";b.src="img/image-placeholder.webp";b.dataset.src=DBHelper.imageUrlForRestaurant(a)+".webp";d.append(b);d=document.createElement("div");d.id="contRest"+g;d.className="column";h.append(d);b=document.createElement("h3");b.innerHTML=a.name;d.append(b);
b=document.createElement("p");b.innerHTML=a.neighborhood;d.append(b);b=document.createElement("p");b.innerHTML=a.address;d.append(b);b=document.createElement("p");b.innerHTML="Favorite: "+a.is_favorite;b.id=l;d.append(b);b=document.createElement("p");b.innerHTML="ID: "+a.id;d.append(b);var f=document.createElement("button");f.className="button";f.id="favBtn"+a.id;f.onclick=function(){"Favorite Me"==f.innerHTML?(e(),console.log("make favorite restaurant id:",g),f.innerHTML="Unfavor"):(k(),console.log("make restaurant UNfavorite"),
f.innerHTML="Favorite Me")};b=document.createElement("a");b.className="button";b.innerHTML="View Details";b.href=DBHelper.urlForRestaurant(a);d.append(b);1==a.is_favorite?(f.innerHTML="Unfavor",console.log("restaurant.is_favorite\x3dtrue")):(f.innerHTML="Favorite Me",console.log("restaurant.is_favorite\x3dfalse"));d.append(f);return h},addMarkersToMap=function(a){a=void 0===a?self.restaurants:a;a.forEach(function(a){var c=DBHelper.mapMarkerForRestaurant(a,self.map);google.maps.event.addListener(c,
"click",function(){window.location.href=c.url});self.markers.push(c)})};
function lazyLoadImages(){console.log("starting lazy load");var a=[].slice.call(document.querySelectorAll("img.lazy"));if("IntersectionObserver"in window){console.log("IntersectionObserver activated for lazy images");var c=new IntersectionObserver(function(a,k){a.forEach(function(a){a.isIntersecting&&(a=a.target,a.src=a.dataset.src,console.log("lazy image: "+a),console.log("IntersectionObserver changed src of lazy img"),a.classList.remove("lazy"),c.unobserve(a))})});a.forEach(function(a){c.observe(a)})}else console.log("lazy load for images did not succeed")}
function loadScript(a,c){var e=document.createElement("script");c&&(e.onload=c);document.getElementsByTagName("head")[0].appendChild(e);e.src=a}var mapUrl="https://maps.googleapis.com/maps/api/js?key\x3dAIzaSyB3Lyq5LfH6rBtpR4SwP02qEdQA01CQfEc\x26libraries\x3dplaces";function initializeMap(){loadScript(mapUrl,function(){map=new google.maps.Map(document.getElementById("map"),{zoom:12,center:{lat:40.722216,lng:-73.987501},scrollwheel:!1});updateRestaurants()})}
function lazyLoadMap(){console.log("starting lazy load");var a=[].slice.call(document.querySelectorAll("#footer"));if("IntersectionObserver"in window){console.log("IntersectionObserver activated for load map");var c=new IntersectionObserver(function(a,k){a.forEach(function(a){a.isIntersecting&&(a=a.target,initializeMap(),c.unobserve(a),console.log("IntersectionObserver  map unobserved"))})});a.forEach(function(a){c.observe(a)})}else console.log("lazy load map did not succeed")}
"serviceWorker"in navigator&&window.addEventListener("load",function(){navigator.serviceWorker.register("sw-min.js").then(function(a){console.log("ServiceWorker registration successful with scope: ",a.scope)},function(a){console.log("ServiceWorker registration failed: ",a)})});